### ISSUE TITLE
Emprunts : Conditionner la possibilité d'emprunter à l'adhésion/la caution

### ISSUE THREAD

**Issue by Emilie31220** [thejoelinux/ludotm#29]

**Comment by thejoelinux** [comment]
Comme on peut toujours avoir des emprunts en cours ou un historique d'emprunt même lorsqu'il n'y a pas d'adhésion ou bien que la caution n'est plus valide, on peut toujours consulter la liste des emprunts.

Par contre, c'est dans cette liste qu'il ne sera pas possible d'en saisir un nouveau.
