### ISSUE TITLE
Changement de la place des "boutons" pour les mettre en haut de la fiche d'emprunts

### ISSUE THREAD

**Issue by Emilie31220** [thejoelinux/ludotm#36]
Est il possible de changer la place des "boutons" ("retour à la fiche adhérents" et nouvel emprunts") dans la fiche des emprunts de chaque adhérents pour les mettre en haut

**Comment by thejoelinux** [comment]
Ok, c'est la même chose sur les adhésions - j'ai noté ça ici, sur l'issue #33 - je note ça pour correction samedi matin.
