### ISSUE TITLE
Impossible de modifier les dates d'adhésions ou de supprimer des adhésions erronées

### ISSUE THREAD

**Issue by Emilie31220** [thejoelinux/ludotm#46]
lorsque je veux modifier une date d'adhésion ou une formule d'adhésion après erreur, j'appuie sur le bouton modifier et un message apparaît : 
Some SQL query has failed.
If you want (and can) you could enable the 'debug' parameter in the config file to know what failed.

**Comment by thejoelinux** [comment]
J'ai trouvé l'erreur, je corrige.
